//Sara D'Iorio
//hw04
//Program2
//Banking

//Write a program using switch statements
//first import scanner class
//then work on goal of allowing users to proccess banking transactions
//start with random amount in account
    //use java.util.Random library or java.lang.Math library
//then offer choice to deposit or withdraw money, or view their balance
    //Deposit -- ask how much (make sure positive)  
        //then print ending balance
    //Withdrawal -- ask how much want to withdraw
        //make sure it's a positive && no more than what's in account
        //then print resulting balance

//import scanner
import java.util.Scanner;

//import and declare class and main method
public class Banking {
//add main method
    public static void main(String[ ] args) {
        Scanner myScanner;
        myScanner = new Scanner(System.in); //define scanner in system
        //generate a randome number between 1000 and 5000 for initial balance
        //use (int)(Math.random()*(upperbound - lower bound)) +lowerbound
        int initialBalance = (int)(Math.random()*(5000-1000)) + 1000;
    
    //Welcome user to bank
        System.out.println("Welcome to Sara D'Iorio's CSE2 Bank");
        System.out.println("Your balance is: $"+initialBalance+"."); //print initial balance generated by java
    
        int optionNumber; //use option numbers (ints) for switch statements (which action will be taken)
        double balance; //cast balance for when we figure out resulting balances
    
        System.out.println ("Please choose from the following menu of what you would like to do"); //prompt choices
        System.out.println ("1: View balance"); //option 1 view balance
        System.out.println ("2: Deposit Money"); //option 2 deposit money
        System.out.println ("3: Withdraw Money"); //option 3 withdraw money
        System.out.print("Type the option number you would like: "); //user input
        optionNumber = myScanner.nextInt(); //accept user choice input


        switch (optionNumber) { //use switch statements
            case 1: //view balance
                System.out.println("Your current balance is: $"+initialBalance+"."); //print balance
                break; //break case 1
            case 2: //deposit
                double amountD; //establish amountD for when we get user input on amount to deposit
                System.out.print("Enter the amount you would like to deposit: $"); //take user amount for deposit
                amountD=myScanner.nextDouble(); //accept user deposit amount
                if (amountD <= 0) { //if statement for if the user put in a negative amount
                    System.out.println("Sorry, you can't deposit nothing or a negative amount."); //system ends, user entered negative amount
                } else { //if user puts in positive amount use else
                    balance = initialBalance + amountD; //calculate the new balance
                    System.out.println("You have depositied $"+amountD+"."); //print amount deposited
                    System.out.println("Your new balance is $"+balance+"."); //print the new balance
                } //close else
                break; //break case 2
            case 3: //withdrawal
                double amountW; //establish amountW for when we get user input on amount to withdraw
                System.out.print("Enter the amound you would like to withdraw: $"); //take user amount for withdrawal
                amountW=myScanner.nextDouble(); //accept user withdrawal amount
                if (amountW <=0 || amountW >=initialBalance) { //if statement for if the user inputs negative number OR more than in their account
                    System.out.println("Sorry, you can't withdraw nothing, a negative amount,"); //system ends, user entered negative amount or more than they have
                    System.out.println("or more than you have in your account."); //finish print statement           
                } else { //if user puts in a valid amount to withdraw
                    balance = initialBalance - amountW; //calculate the new balance
                    System.out.println("You have withdrawn $"+amountW+"."); //print amount withdrawn
                    System.out.println("Your new balance is $"+balance+"."); //print new balance
                } //close else
                break; //break case 3
                
            default: //for input other than the option
                System.out.println("You have entered an invalid input. Please start again."); 
                //user entered something other than the options, system defaults to end
        } //end switch statement
    
        System.out.println("Thank you for using Sara D'Iorio's CSE2 Bank. Have a nice day!");
            //system goodbye message
                
            
    } //end main method
} //end class

